services:
  - type: web
    name: excalidraw-http-backend
    env: node
    buildCommand: pnpm install && pnpm --filter http-backend build
    startCommand: node apps/http-backend/dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3002

  - type: web
    name: excalidraw-ws-backend
    env: node
    buildCommand: pnpm install && pnpm --filter ws-backend build
    startCommand: node apps/ws-backend/dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8081

  - type: web
    name: excalidraw-frontend
    env: node
    buildCommand: pnpm install && pnpm --filter excelidraw-frontend build
    startCommand: pnpm --filter excelidraw-frontend start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_WS_URL
        sync: false
